part of '../cli_commands.dart';

/// Start create linux icons
void createLinuxIcons({required String imagePath}) {
  CliLogger.info('Creating Linux icons...', emoji: '🐧');

  final image = Icon.loadFile(imagePath);
  if (image == null) {
    CliLogger.error('The file $imagePath could not be read.', level: .two);
    exit(1);
  }

  // icon and .desktop file name must be the same as your app name in yaml file
  final appName = _readAppNameFromYaml();
  final appVersion = _readAppVersionFromYaml();
  final iconFileName = '$appName.png';

  final template = LinuxIconTemplate(name: appName, size: 256);
  _saveImageLinux(template, image, iconFileName);
  CliLogger.success('Generated app icon image', level: .two);

  // Create snapcraft.yaml file
  final snapcraftFile = File('${LINUX_DEFAULT_SNAP_DIR}snapcraft.yaml');
  if (!snapcraftFile.existsSync()) {
    _createSnapcraftFile(appName, appVersion);
    CliLogger.success('Created snapcraft file', level: .two);
  } else {
    CliLogger.warning('Snapcraft file already exists', level: .two);
  }

  // Create desktop entry file
  final desktopFile = File('$LINUX_DEFAULT_ICON_DIR$appName.desktop');
  if (!desktopFile.existsSync()) {
    _createLinuxDesktopFile(appName);
    CliLogger.success('Created desktop entry file', level: .two);
  } else {
    CliLogger.warning('Desktop entry file already exists', level: .two);
  }
}

/// Read app name from pubspec.yaml
String _readAppNameFromYaml() {
  final file = File('pubspec.yaml');
  if (file.existsSync()) {
    final yamlMap = loadYaml(file.readAsStringSync()) as Map;
    if (yamlMap['name'] is String) {
      return yamlMap['name'] as String;
    }
  }
  return LINUX_DEFAULT_APP_NAME;
}

/// Read app version from pubspec.yaml
String _readAppVersionFromYaml() {
  final file = File('pubspec.yaml');
  if (file.existsSync()) {
    final yamlMap = loadYaml(file.readAsStringSync()) as Map;
    if (yamlMap['version'] is String) {
      final rawVersion = yamlMap['version'] as String;
      final version = rawVersion.split('+')[0];
      return version;
    }
  }
  return LINUX_DEFAULT_APP_VERSION;
}

/// Save linux image
void _saveImageLinux(LinuxIconTemplate template, Icon image, String fileName) {
  image.saveResizedPng(template.size, '$LINUX_DEFAULT_ICON_DIR$fileName');
}

/// Create snapcraft.yaml file
void _createSnapcraftFile(String appName, String appVersion) {
  final snapcraftFile =
      '''
name: $appName
version: $appVersion
summary: Generated by Icons Launcher
description: Generated by Icons Launcher package for Linux.

confinement: strict
base: core22
grade: stable

slots:
  dbus-$appName: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.$appName # adjust accordingly to your app name

apps:
  $appName:
    command: $appName
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
    - network
    slots:
      - dbus-$appName
parts:
  $appName:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
''';

  final file = File('${LINUX_DEFAULT_SNAP_DIR}snapcraft.yaml');
  file.createSync(recursive: true);
  file.writeAsStringSync(snapcraftFile);
}

/// Create linux desktop file
void _createLinuxDesktopFile(String appName) {
  final desktopFile =
      '''
[Desktop Entry]
Name=$appName
Comment=Generated by Icons Launcher
Exec=$appName
Icon=\${SNAP}/meta/gui/$appName.png
Terminal=false
Type=Application
Categories=Entertainment;
''';

  final file = File('$LINUX_DEFAULT_ICON_DIR$appName.desktop');
  file.createSync(recursive: true);
  file.writeAsStringSync(desktopFile);
}
